#!/usr/bin/env node
// install_memory_seeds.mjs
// For each applicable memory seed in memory-seeds/, write a wrapper memory
// entry into the target's Claude memory folder. Idempotent: re-runs skip
// already-wrapped seeds unless --force. On --update, regenerate only the
// above-marker section of existing wrappers.
//
// Seed applicability: if a seed's frontmatter `tags` block declares
// language/testing/platform, the seed installs only when every declared tag
// is present in ops.config.json -> stack.*.
//
// Usage:
//   node install_memory_seeds.mjs --target <path> [--memory-dir <path>]
//     [--dry-run | --apply | --update] [--force] [--emit-manifest]
//
// Frontmatter parsing uses `gray-matter` (real YAML), not a fragile regex.
// Helpers (parseSeed, seedApplies, buildHeaderForMemory) are exported so
// unit tests can exercise them without spawning a child process.

import { readFile, readdir } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import matter from "gray-matter";
import { preflight } from "./preflight.mjs";
import { parseArgv, boolFlag } from "./lib/argv.mjs";
import {
  atomicWriteText,
  ensureDir,
  readJsonOrNull,
  readTextOrNull,
  safeRealpathOrExit,
  sha256,
} from "./lib/fsx.mjs";
import { splitAtMarker } from "./lib/wrapper.mjs";
import { getAgentPrefix, prefixed } from "./lib/agentName.mjs";

// --- exported helpers ----------------------------------------------------

/**
 * Parse a seed's frontmatter + body. Returns `{ name, description, type, tags }` or null
 * when the file has no frontmatter.
 */
export function parseSeed(text) {
  // Strip an optional UTF-8 BOM; gray-matter does not do this.
  const stripped = text.replace(/^\uFEFF/, "");
  let parsed;
  try {
    parsed = matter(stripped);
  } catch {
    return null;
  }
  if (!parsed.data || Object.keys(parsed.data).length === 0) return null;
  const data = parsed.data;
  const tags = { language: [], testing: [], platform: [] };
  const raw = data.tags;
  if (raw && typeof raw === "object" && !Array.isArray(raw)) {
    for (const axis of ["language", "testing", "platform"]) {
      const v = raw[axis];
      if (v == null) continue;
      if (Array.isArray(v)) tags[axis] = v.map(String);
      else tags[axis] = [String(v)];
    }
  }
  return {
    name: typeof data.name === "string" ? data.name.trim() : "",
    description: typeof data.description === "string" ? data.description.trim() : "",
    type: typeof data.type === "string" ? data.type.trim() : "feedback",
    tags,
  };
}

/** Is a seed's tag block satisfied by the project's stack? */
export function seedApplies(seedTags, stack) {
  const has = (axis, v) => (stack[axis] ?? new Set()).has(v);
  for (const axis of ["language", "testing", "platform"]) {
    const needed = seedTags[axis] ?? [];
    if (needed.length > 0 && !needed.every((t) => has(axis, t))) return false;
  }
  return true;
}

/** Collect stack tags from ops.config.json -> stack.*. */
export function collectStackTags(stack) {
  return {
    language: new Set(stack?.language ?? []),
    testing: new Set(stack?.testing ?? []),
    platform: new Set(stack?.platform ?? []),
  };
}

/** Pretty one-liner for "seed needs language=swift + testing=xcuitest". */
export function formatTags(tags) {
  const parts = [];
  if (tags.language.length) parts.push(`language=${tags.language.join(",")}`);
  if (tags.testing.length) parts.push(`testing=${tags.testing.join(",")}`);
  if (tags.platform.length) parts.push(`platform=${tags.platform.join(",")}`);
  return parts.length ? parts.join(" + ") : "(no stack tags)";
}

/** Render the above-marker section of a memory wrapper. */
export function buildHeaderForMemory(seed, canonicalRel, headerNotice) {
  const name = seed.name || seed.fileBase || "unnamed";
  const fm = [
    "---",
    `name: [seed] ${name}`,
    `description: ${seed.description} (canonical at ${canonicalRel})`,
    `type: ${seed.type}`,
    `source: ${canonicalRel}`,
    `source_role: wrapper`,
    "---",
  ].join("\n");
  return [
    fm,
    "",
    `<!-- ${headerNotice} -->`,
    "",
    `Before acting on this memory, read and follow the canonical seed at:`,
    `\`${canonicalRel}\``,
    "",
    `That file updates when you run 'git pull' inside the agent bundle.`,
    `This wrapper's above-marker section is regenerated by 'install_memory_seeds.mjs --update'.`,
    `Anything you place below the overrides marker is preserved across updates.`,
  ].join("\n");
}

/** Slugify a seed filename so the wrapper path is always valid. */
export function slugifyFilename(name) {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9._-]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

// --- CLI entrypoint ------------------------------------------------------

// Guard: if this file is being imported (by a test) rather than executed
// directly, stop here so tests can import helpers without triggering the
// interactive/mutative install flow.
const isDirectRun = import.meta.url === pathToFileURL(process.argv[1] ?? "").href;
if (isDirectRun) {
  await main();
}

async function main() {
  await preflight();

  const { flags } = parseArgv(process.argv.slice(2), {
    booleans: new Set(["dry-run", "apply", "update", "force", "yes", "help", "emit-manifest"]),
  });
  if (flags.help) {
    printHelp();
    process.exit(0);
  }

  const TARGET = await safeRealpathOrExit(resolve(flags.target ?? "."), "target");
  const BUNDLE_ROOT = await safeRealpathOrExit(resolve(dirname(fileURLToPath(import.meta.url)), ".."), "bundle");
  const { prefix: AGENT_PREFIX } = await getAgentPrefix(BUNDLE_ROOT);
  const APPLY = boolFlag(flags, "apply", false) || boolFlag(flags, "update", false);
  const UPDATE = boolFlag(flags, "update", false);
  const FORCE = boolFlag(flags, "force", false);
  const DRY_RUN = !APPLY;

  const memoryDir = resolve(flags["memory-dir"] ?? join(TARGET, ".claude", "memory"));
  const opsConfig = await readJsonOrNull(join(TARGET, ".claude/ops.config.json"));
  if (!opsConfig) {
    process.stderr.write(
      `install_memory_seeds: ${join(TARGET, ".claude/ops.config.json")} not found. Run bootstrap first.\n`
    );
    process.exit(1);
  }

  const marker = opsConfig.paths?.wrappers?.marker ?? DEFAULT_MARKER;
  const headerNotice = opsConfig.paths?.wrappers?.header_notice ?? DEFAULT_HEADER_NOTICE;
  const stackTags = collectStackTags(opsConfig.stack ?? {});

  const seedsDir = join(BUNDLE_ROOT, "memory-seeds");
  const canonicalSeeds = [];
  for (const filename of await readdir(seedsDir)) {
    if (!filename.endsWith(".md")) continue;
    const fp = join(seedsDir, filename);
    const text = await readFile(fp, "utf8");
    const parsed = parseSeed(text);
    if (!parsed) continue;
    canonicalSeeds.push({
      ...parsed,
      filename,
      fileBase: filename.replace(/\.md$/, ""),
      path: fp,
    });
  }

  const applicable = canonicalSeeds.filter((s) => seedApplies(s.tags, stackTags));
  const skipped = canonicalSeeds.filter((s) => !seedApplies(s.tags, stackTags));

  process.stdout.write(`target memory dir: ${memoryDir}\n`);
  process.stdout.write(`seeds total:        ${canonicalSeeds.length}\n`);
  process.stdout.write(`seeds applicable:   ${applicable.length}\n`);
  process.stdout.write(`seeds skipped:      ${skipped.length} (stack tags unmet)\n`);
  for (const s of skipped) process.stdout.write(`  - ${s.filename}: needs ${formatTags(s.tags)}\n`);
  process.stdout.write("\n");

  const writes = [];
  for (const seed of applicable) {
    const baseFilename = seed.fileBase || slugifyFilename(seed.name || "seed");
    const wrapperPath = join(memoryDir, `seed-${prefixed(AGENT_PREFIX, baseFilename)}.md`);
    const canonicalRel = relBundlePath(TARGET, opsConfig, seed.path, BUNDLE_ROOT);
    const header = buildHeaderForMemory(seed, canonicalRel, headerNotice);
    const above = `${header}\n${marker}\n`;
    const existing = await readTextOrNull(wrapperPath);
    let finalContent;
    if (existing == null) {
      finalContent = `${above}\n`;
    } else {
      const { above: oldAbove } = splitAtMarker(existing, marker);
      if (!UPDATE && !FORCE) {
        writes.push({ path: wrapperPath, action: "skip (exists)", content: null });
        continue;
      }
      if (UPDATE && oldAbove == null) {
        writes.push({
          path: wrapperPath,
          action: "skip (no marker; orphan)",
          content: null,
          warn: true,
        });
        continue;
      }
      const after = existing.slice(existing.indexOf(marker) + marker.length);
      finalContent = `${above}\n${after.replace(/^\n+/, "\n")}`;
    }
    writes.push({
      path: wrapperPath,
      action: existing == null ? "create" : UPDATE ? "refresh (above marker)" : "overwrite (--force)",
      content: finalContent,
      canonical: canonicalRel,
      sha: sha256(finalContent),
    });
  }

  printPlan(writes);

  if (DRY_RUN) {
    process.stdout.write("\n(dry-run) no writes performed. Re-run with --apply or --update.\n");
    process.exit(0);
  }

  for (const w of writes) {
    if (w.content == null) continue;
    await ensureDir(dirname(w.path));
    await atomicWriteText(w.path, w.content);
  }
  process.stdout.write(`wrote ${writes.filter((w) => w.content != null).length} wrapper(s).\n`);

  if (flags["emit-manifest"]) {
    for (const w of writes) {
      if (w.content == null) continue;
      const entry = {
        path: w.path,
        kind: "memory-seed-wrapper",
        canonical: w.canonical,
        sha: w.sha,
        written_at: new Date().toISOString(),
      };
      process.stdout.write(`__MANIFEST__ ${JSON.stringify(entry)}\n`);
    }
  }
}

const DEFAULT_MARKER =
  "<!-- ============ PROJECT OVERRIDES BELOW (preserved across agent updates) ============ -->";
const DEFAULT_HEADER_NOTICE =
  "Wrapper file. Canonical content lives in the agent bundle and updates via 'git pull' inside the bundle. Edit below the overrides marker only; everything above is regenerated.";

function printHelp() {
  process.stdout.write(
    [
      "install_memory_seeds.mjs  install wrapper memory entries for applicable seeds",
      "",
      "Options:",
      "  --target <path>        target project root (default: cwd)",
      "  --memory-dir <path>    target's Claude memory folder",
      "                         (default: <target>/.claude/memory)",
      "  --dry-run              default; print plan, do not write",
      "  --apply                write any missing wrappers",
      "  --update               refresh above-marker section of existing wrappers",
      "  --force                overwrite even non-marker wrappers (dangerous)",
      "  --emit-manifest        print one __MANIFEST__ <json> line per write,",
      "                         for install.mjs to fold into .install-manifest.json",
      "",
    ].join("\n")
  );
}

function relBundlePath(target, cfg, absInsideBundle, bundleRoot) {
  const bundleDir = cfg.paths?.agent_bundle_dir;
  // If bundleDir is a project-relative path, keep it so; otherwise use the
  // absolute bundle root.
  const refRoot = bundleDir && !bundleDir.startsWith("..") && !bundleDir.startsWith("/")
    ? bundleDir
    : bundleRoot;
  const bundleAbs = resolve(target, refRoot);
  const rel = relative(bundleAbs, absInsideBundle).split(/[\\/]+/).join("/");
  return `${refRoot}/${rel}`;
}

function printPlan(plan) {
  process.stdout.write("plan\n");
  for (const w of plan) {
    const sha = w.sha ? ` sha=${w.sha.slice(0, 8)}` : "";
    process.stdout.write(`  ${w.action.padEnd(32)} ${w.path}${sha}${w.warn ? " !warn" : ""}\n`);
  }
}
